server:
  port: 5000
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
jwt:
  claimKey:
    username: "username"
    authorities: "authorities"
  secret: "wfhg9hr-1jfpjf-p3j-=vgf0pvmo3k=2-3rj0-3j=gn[=3-g[mj"
  header: Authorization
  tokenHead: "Bearer "
oos:
  accessKey: "c4582dec5d0809103126"
  secretKey: "47c783687d4c452c5d71b817b8c481915fb0094a"
  endPoint: "http://oos-bj2.ctyunapi.cn"
  bucketName: "mycourses"
email:
  sender: "18851822162@163.com"
  subject: "ChainPaper账号注册邮箱认证"
  content1: "亲爱的用户： 您好!
            您正在注册ChainPaper账号，请在验证码输入框中输入："
  content2: "以完成注册。"
spring:
  jpa:
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chainpaper?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  aop:
    auto: true
    proxy-target-class: false
  mail:
    host: smtp.163.com
    username: 18851822162@163.com
    password: 999959
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    jndi-name: mail